language: node_js
node_js: node

install:
  - npm install -g elm

script:
  - elm make src/Main.elm --output=index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
